# Generated by Django 4.1.5 on 2023-01-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField()),
                ('data', models.DateField()),
                ('valor', models.FloatField()),
                ('cpf', models.CharField(max_length=11)),
                ('cartao', models.CharField(max_length=12)),
                ('hora', models.TimeField()),
                ('donoLoja', models.CharField(max_length=14)),
                ('nomeLoja', models.CharField(max_length=19)),
            ],
        ),
    ]
