# Generated by Django 4.1.5 on 2023-01-26 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='cartao',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='data',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='hora',
            new_name='hour',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='tipo',
            new_name='type_transaction',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='valor',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='donoLoja',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='nomeLoja',
        ),
        migrations.AddField(
            model_name='transaction',
            name='store',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='stores.store'),
            preserve_default=False,
        ),
    ]
